import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import './globals.css'
import { Header } from '../components/header'
import { Sidebar } from '@/components/sidebar'

const inter = Inter({
  subsets: ['latin'],
  display: 'auto',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <div className="h-screen">
          <Header />
          <Sidebar />
          {children}
        </div>
      </body>
    </html>
  )
}
